# Generated by Django 2.2.10 on 2020-03-06 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_dont_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='dont_contact',
            field=models.BooleanField(default=False, help_text='I do not want to be contacted by the admin for questions about my M-plates', verbose_name='Do not contact me'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, help_text='Optional. Password recovery can only be done with a valid e-mail address.', max_length=254, unique=True, verbose_name='E-mail address'),
        ),
    ]
