# Generated by Django 2.2.10 on 2020-03-06 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200306_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='dont_contact',
            field=models.BooleanField(default=False, help_text='I do not want to be contacted by the admin for questions about my M-plates.', verbose_name='Do not contact me'),
        ),
    ]
