# Generated by Django 2.2.10 on 2020-03-06 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200306_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, help_text='Optional. Password recovery can only be done with a valid e-mail address.', max_length=254, null=True, unique=True, verbose_name='E-mail address'),
        ),
    ]
