"""
Django settings for vw_type2_id project.

Generated by 'django-admin startproject' using Django 2.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os
import dj_database_url
import sentry_sdk
from pathlib import Path
from sentry_sdk.integrations.django import DjangoIntegration


def secret(name, env_var):
    """Read the container secret /run/secrets/<name>, else env_var."""
    path = Path('/run/secrets') / name
    if path.exists():
        return path.read_text().strip()
    return os.environ.get(env_var)


SENTRY_DSN = secret('vw-sentry-dsn', 'SENTRY_DSN')
if SENTRY_DSN:
    sentry_sdk.init(
        dsn=SENTRY_DSN,
        integrations=[DjangoIntegration()],
        traces_sample_rate=1.0,
        send_default_pii=True,
    )

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
# This is the top-level root
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# This is the site root under the top-level root
PROJECT_ROOT = os.path.dirname(os.path.abspath(__file__))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

SECRET_KEY = secret('vw-secret-key', 'DJANGO_VW_TYPE2_ID_SECRET_KEY')

DEBUG = int(os.environ.get('DJANGO_DEBUG', default=0))

# Commit the running image was built from, set at build time
GIT_COMMIT = os.environ.get('GIT_COMMIT', '')

ALLOWED_HOSTS = os.environ.get(
    'DJANGO_ALLOWED_HOSTS',
    default='localhost 127.0.0.1').split(' ')

# Behind a reverse proxy that terminates TLS and redirects HTTP to HTTPS
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
# HSTS covers this domain only, not subdomains or the preload list
SILENCED_SYSTEM_CHECKS = ['security.W005', 'security.W008', 'security.W021']
if not DEBUG:
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'django.contrib.sitemaps',
    'mplate_decoder.apps.MplateDecoderConfig',
    'crispy_forms',
    'crispy_bootstrap4',
    'fullurl',
    'markdownify',
    'users',
    'contact.apps.ContactConfig',
    'vinaigrette',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'crum.CurrentRequestUserMiddleware',
    'vinaigrette.middleware.VinaigretteAdminLanguageMiddleware',
]

ROOT_URLCONF = 'vw_type2_id.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(PROJECT_ROOT, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'vw_type2_id.context_processors.git_commit',
            ],
            'debug': DEBUG,
        },
    },
]

WSGI_APPLICATION = 'vw_type2_id.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases
DATABASES = {'default': dj_database_url.parse(
    secret('vw-database-url', 'DATABASE_URL')
    or f"sqlite:///{os.path.join(BASE_DIR, 'db.sqlite3')}")}

# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator', # noqa
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator', # noqa
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator', # noqa
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator', # noqa
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/
# The default will find files:
# - stored in the STATICFILES_DIRS setting
# - and in a static subdirectory of each app

# URL to use when referring to static files located in STATIC_ROOT.
STATIC_URL = '/static/'

# The absolute path to the directory where collectstatic
# will collect static files for deployment.
STATIC_ROOT = os.path.join(BASE_DIR,
                           STATIC_URL.replace('/', ''))

# For static assets not tied to a particular app
STATICFILES_DIRS = [
    os.path.join(PROJECT_ROOT, "static"),
]

STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedStaticFilesStorage',
    },
}

CRISPY_ALLOWED_TEMPLATE_PACKS = 'bootstrap4'
CRISPY_TEMPLATE_PACK = 'bootstrap4'

MARKDOWNIFY = {
    'default': {
        'BLEACH': False,
    },
}

# Generate jUnit test reports
TEST_RUNNER = 'xmlrunner.extra.djangotestrunner.XMLTestRunner'
TEST_OUTPUT_DIR = 'test-results'

# This tells Django that instead of using the default
# User model look in our app users for the model called CustomUser
# and use that instead everywhere in our project.
AUTH_USER_MODEL = 'users.CustomUser'

LOGIN_REDIRECT_URL = 'mplate_decoder:mplate_index'
LOGOUT_REDIRECT_URL = 'mplate_decoder:mplate_index'

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
DEFAULT_FROM_EMAIL = os.environ.get('DJANGO_VW_TYPE2_EMAIL',
                                    'VW Type 2 ID <no-reply@vw-type2-id.xyz>')
CONTACT_EMAIL = os.environ.get('DJANGO_CONTACT_EMAIL',
                               'contact@vw-type2-id.xyz')
EMAIL_HOST = os.environ.get('DJANGO_EMAIL_HOST', 'localhost')
EMAIL_PORT = int(os.environ.get('DJANGO_EMAIL_PORT', 25))
EMAIL_HOST_USER = os.environ.get('DJANGO_EMAIL_USER', '')
EMAIL_HOST_PASSWORD = secret('vw-email-password', 'DJANGO_EMAIL_PASSWORD')
EMAIL_USE_TLS = bool(int(os.environ.get('DJANGO_EMAIL_USE_TLS', 0)))

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'standard': {
            'format': '[{asctime}] {levelname} [{name}:{lineno}] '
                      '{message}',
            'datefmt': '%d/%b/%Y %H:%M:%S',
            'style': '{',
        },
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} '
                      '{thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
        'server': {
            '()': 'django.utils.log.ServerFormatter',
            'format': '[{server_time}] {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'level': os.getenv('DJANGO_LOG_LEVEL', 'INFO'),
            'class': 'logging.StreamHandler',
            'formatter': 'standard',
        },
    },
    'loggers': {
        'mplate_decoder': {
            'handlers': ['console'],
            'level': os.getenv('DJANGO_LOG_LEVEL', 'INFO'),
            'propagate': True,
        },
    },
}

DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

# Create a single set of PO files on this directory
# It allows us to run the makemessages command at the root
# directory
LOCALE_PATHS = (
    PROJECT_ROOT + '/locale', )


# Default language used when Django cannot recognize user's language.
LANGUAGE_CODE = 'en-us'
