stages:
  - build
  - test
  - deploy
  - dast

include:
  - template: Dependency-Scanning.gitlab-ci.yml
  - template: DAST.gitlab-ci.yml
  - template: License-Management.gitlab-ci.yml
  - template: SAST.gitlab-ci.yml
  - template: Code-Quality.gitlab-ci.yml

variables:
  DAST_WEBSITE: https://vw-type2-id.xyz/mplate/decode
  WHEEL_DIR: ./dist

cache:
  paths:
    - ~/.cache/pip/
    - ~/.cache/pipenv/

default:
  image: python:3.6

.linter_template:
  stage: test
  before_script:
    - pip3 install pipenv
    - pipenv install --dev

# Required for dependency scanning to work: build the binaries for the libraries
# needed to build native pip dependencies
build_dep_wheels:
  stage: build
  script:
    - pip wheel --no-binary=':all:' --wheel-dir $WHEEL_DIR -r requirements.txt
  artifacts:
    paths:
      - $WHEEL_DIR

# Override the dependency_scanning job to use PIP_DEPENDENCY_PATH and find
# the binaries required to build the native pip dependencies
dependency_scanning:
  dependencies:
    - build_dep_wheels
  variables:
    PIP_DEPENDENCY_PATH: $WHEEL_DIR
  artifacts:
    paths: [gl-dependency-scanning-report.json]

# Override the code_quality job to make the code quality report artifact
# downloadable from the job detail page
code_quality:
  artifacts:
    paths: [gl-code-quality-report.json]

flake8:
  extends: .linter_template
  script:
  - pipenv run flake8 --exclude=migrations

pylint:
  extends: .linter_template
  script:
  - pipenv run pylint **/*.py --ignore=migrations
  allow_failure: true

test_apps:
  stage: test
  before_script:
    - wget https://github.com/mozilla/geckodriver/releases/download/v0.25.0/geckodriver-v0.25.0-linux64.tar.gz
    - tar -xzf geckodriver-v0.25.0-linux64.tar.gz -C /usr/local/bin
    - geckodriver --version
    - apt-get update && apt-get install -y xvfb firefox-esr x11-utils
    - pip3 install pipenv
    - pipenv install --dev
  script:
    - pipenv run coverage run --source='.' manage.py test --verbosity 2
    - pipenv run coverage report
    - pipenv run coverage html
  variables:
    DJANGO_VW_TYPE2_ID_SECRET_KEY: "dummy_secret_key_testing"
    MOZ_HEADLESS: "1"
  artifacts:
    paths:
      - htmlcov/
      - test-results/
    reports:
      junit: ./test-results/TEST-*.xml

pages:
  stage: deploy
  dependencies:
    - test_apps
  script:
    - mv htmlcov/ public/
  artifacts:
    paths:
      - public
    expire_in: 30 days
  only:
    - master
