[pytest]
DJANGO_SETTINGS_MODULE = vw_type2_id.settings
addopts = -v
filterwarnings =
    error::django.utils.deprecation.RemovedInNextVersionWarning
    error::django.utils.deprecation.RemovedAfterNextVersionWarning
