from pathlib import Path

from django.core.management.base import BaseCommand

from mplate_decoder.models import (
    Color, Engine, ExportDestination, Gearbox, InteriorColor, Mcode,
)

TRANSLATED_FIELDS = {
    Mcode: ['description', 'remarks'],
    Engine: ['engine_type', 'fuel_induction', 'extra_specs'],
    Gearbox: ['gearbox_description'],
    Color: ['color_name'],
    InteriorColor: ['color_name', 'material'],
    ExportDestination: ['country'],
}

OUTPUT = Path(__file__).resolve().parents[2] / 'db_strings.py'

HEADER = '''\
# Translatable strings from the reference tables, for makemessages.
# Generated by "python manage.py export_db_strings". Do not edit.
# flake8: noqa
from django.utils.translation import gettext_noop

'''


class Command(BaseCommand):
    help = ('Write the translatable reference data strings to '
            'mplate_decoder/db_strings.py')

    def handle(self, *args, **options):
        """Write each distinct non-empty value once, sorted."""
        strings = set()
        for model, fields in TRANSLATED_FIELDS.items():
            for row in model.objects.values_list(*fields):
                strings.update(value.replace('\r', '')
                               for value in row if value)

        lines = [f'gettext_noop({s!r})\n' for s in sorted(strings)]
        OUTPUT.write_text(HEADER + ''.join(lines), encoding='utf-8')
        self.stdout.write(f'Wrote {len(lines)} strings to {OUTPUT}')
