# Generated by Django 2.2.4 on 2019-08-17 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mplate_decoder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcode',
            name='is_special_code',
            field=models.BooleanField(default=False),
        ),
    ]
