# Generated by Django 2.2.4 on 2019-08-20 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mplate_decoder', '0003_mcode_model_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mplate',
            name='m_codes_2',
            field=models.CharField(blank=True, help_text="Row 2 of M codes (max 4 -mod. '70-'79 or 5 -mod. '68-'69-)", max_length=19),
        ),
    ]
