# Generated by Django 2.2.4 on 2019-08-22 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mplate_decoder', '0004_auto_20190820_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='exportdestination',
            name='country',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exportdestination',
            name='notes',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='exportdestination',
            name='port',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='exportdestination',
            name='region',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='mcode',
            name='editor_remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='mcode',
            name='source',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='mcodecollection',
            name='editor_remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='mcodecollection',
            name='source',
            field=models.TextField(blank=True),
        ),
    ]
