# Generated by Django 2.2.8 on 2020-01-01 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mplate_decoder', '0005_auto_20190822_1807'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exportdestination',
            old_name='export_destination',
            new_name='destination',
        ),
        migrations.AddField(
            model_name='exportdestination',
            name='city',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
