# Generated by Django 2.2.8 on 2020-01-02 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mplate_decoder', '0007_auto_20200102_0541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exportdestination',
            name='country',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
