# Generated by Django 2.2.8 on 2020-01-26 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mplate_decoder', '0008_auto_20200102_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='mplate',
            name='plate_version',
            field=models.CharField(blank=True, help_text='M-plate format\n            version', max_length=3),
        ),
    ]
