# Generated by Django 2.2.8 on 2020-02-16 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mplate_decoder', '0008_auto_20200102_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='mplate',
            name='m_codes',
            field=models.CharField(blank=True, help_text='Full list of M codes for this M plate', max_length=38),
        ),
    ]
