# Generated by Django 2.2.8 on 2020-02-16 23:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mplate_decoder', '0009_mplate_m_codes'),
    ]

    operations = [
        migrations.AddField(
            model_name='mplate',
            name='production_date_as_time',
            field=models.DateField(blank=True, default=django.utils.timezone.now, help_text='Planned production date, in time format'),
            preserve_default=False,
        ),
    ]
