# Generated by Django 2.2.8 on 2020-02-16 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mplate_decoder', '0010_mplate_production_date_as_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mplate',
            name='m_codes',
            field=models.CharField(blank=True, editable=False, help_text='Full list of M codes for this M plate', max_length=38),
        ),
        migrations.AlterField(
            model_name='mplate',
            name='production_date_as_time',
            field=models.DateField(blank=True, editable=False, help_text='Planned production date, in time format'),
        ),
    ]
