# Generated by Django 2.2.8 on 2020-02-16 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mplate_decoder', '0011_auto_20200216_2351'),
    ]

    operations = [
        migrations.AddField(
            model_name='mplate',
            name='model_year',
            field=models.CharField(blank=True, editable=False, help_text='Model year', max_length=4),
        ),
    ]
