# Generated by Django 2.2.8 on 2020-02-29 01:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mplate_decoder', '0012_mplate_model_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='mplate',
            name='owner',
            field=models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
