# Generated by Django 2.2.8 on 2020-02-29 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mplate_decoder', '0013_mplate_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='mplate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='mplate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
