# Generated by Django 2.2.10 on 2020-03-04 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mplate_decoder', '0014_auto_20200229_2129'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mplate',
            options={'ordering': ['-id']},
        ),
    ]
