# Generated by Django 2.2.11 on 2020-03-07 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mplate_decoder', '0016_mplate_editor_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='mplate',
            name='destination_country',
            field=models.CharField(blank=True, help_text='Country of destination', max_length=30),
        ),
    ]
