# Generated by Django 2.2.11 on 2020-03-15 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mplate_decoder', '0017_mplate_destination_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='VwType2Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.PositiveSmallIntegerField()),
                ('configuration', models.PositiveSmallIntegerField()),
                ('extras', models.PositiveSmallIntegerField()),
                ('model_description', models.CharField(help_text='Model description', max_length=35)),
                ('configuration_description', models.TextField()),
                ('m_codes', models.CharField(blank=True, help_text='List of M-codes for the corresponding extras', max_length=50)),
                ('chassis_plate', models.CharField(blank=True, help_text='Model description as it appears on the chassis plate', max_length=20)),
                ('years', models.CharField(blank=True, max_length=65)),
                ('schematic_bitmap', models.TextField(blank=True)),
                ('schematic_vector', models.TextField(blank=True)),
            ],
        ),
    ]
