# Generated by Django 2.2.11 on 2020-03-15 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mplate_decoder', '0018_vwtype2model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vwtype2model',
            name='schematic_bitmap',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
