# Generated by Django 2.2.11 on 2020-03-15 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mplate_decoder', '0019_auto_20200315_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='vwtype2model',
            name='extras_description',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
