# Generated by Django 2.2.11 on 2020-03-29 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mplate_decoder', '0020_vwtype2model_extras_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vwtype2model',
            name='schematic_bitmap',
        ),
        migrations.AddField(
            model_name='color',
            name='editor_remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='engine',
            name='editor_remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='exportdestination',
            name='editor_remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='exteriorcolor',
            name='editor_remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='interiorcolor',
            name='editor_remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vwtype2model',
            name='editor_remarks',
            field=models.TextField(blank=True),
        ),
    ]
