# Generated by Django 2.2.11 on 2020-03-29 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mplate_decoder', '0021_auto_20200329_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcode',
            name='collection',
            field=models.TextField(blank=True),
        ),
    ]
