# Generated by Django 2.2.11 on 2020-04-05 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mplate_decoder', '0022_mcode_collection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mplate',
            name='paint_and_interior',
            field=models.CharField(default='', help_text='Combined VW body/roof paint and interior codes', max_length=6, verbose_name='Paint and interior'),
            preserve_default=False,
        ),
        migrations.RenameField(
            model_name='mplate',
            old_name='paint_and_interior',
            new_name='paint_and_interior_code',
        ),
        migrations.AlterField(
            model_name='mplate',
            name='aggregate_code',
            field=models.CharField(help_text='Engine and gearbox aggregate code', max_length=2, verbose_name='Agggregate'),
        ),
        migrations.AlterField(
            model_name='mplate',
            name='chassis_number_short',
            field=models.CharField(help_text='Chassis number shortened, with the two leading digits removed.', max_length=8, unique=True, verbose_name='Shortened chassis number'),
        ),
        migrations.AlterField(
            model_name='mplate',
            name='emden',
            field=models.CharField(blank=True, help_text='Optional "E" for Emden', max_length=1, verbose_name='Emden'),
        ),
        migrations.AlterField(
            model_name='mplate',
            name='export_destination',
            field=models.CharField(blank=True, help_text='Export destination code', max_length=3, verbose_name='Export destination'),
        ),
        migrations.AlterField(
            model_name='mplate',
            name='m_codes_1',
            field=models.CharField(blank=True, help_text='Row 1 of M codes (max 5)', max_length=19, verbose_name='M-codes, row 1'),
        ),
        migrations.AlterField(
            model_name='mplate',
            name='m_codes_2',
            field=models.CharField(blank=True, help_text="Row 2 of M codes (max 4 -mod. '70-'79 or 5 -mod. '68-'69-)", max_length=19, verbose_name='M-codes, row 2'),
        ),
        migrations.AlterField(
            model_name='mplate',
            name='model',
            field=models.CharField(help_text='Vehicle model code', max_length=4, verbose_name='Model'),
        ),
        migrations.AlterField(
            model_name='mplate',
            name='production_date',
            field=models.CharField(help_text='Production date code', max_length=3, verbose_name='Production date'),
        ),
        migrations.AlterField(
            model_name='mplate',
            name='production_planned',
            field=models.CharField(blank=True, help_text='Production planning code', max_length=4, verbose_name='Production planning'),
        ),
    ]
