# Generated by Django 2.2.11 on 2020-04-05 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mplate_decoder', '0023_auto_20200405_0843'),
    ]

    operations = [
        migrations.AddField(
            model_name='exteriorcolor',
            name='lacquer_code_body_link',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lacquer_code_body', to='mplate_decoder.Color'),
        ),
        migrations.AddField(
            model_name='exteriorcolor',
            name='lacquer_code_roof_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lacquer_code_roof', to='mplate_decoder.Color'),
        ),
    ]
