# Generated by Django 2.2.11 on 2020-04-05 14:16

from django.db import migrations


def link_colors(apps, schema_editor):
    ExteriorColor = apps.get_model('mplate_decoder', 'ExteriorColor')
    Color = apps.get_model('mplate_decoder', 'Color')
    for exteriorcolor in ExteriorColor.objects.all():
        lacquer_code_body, created = Color.objects.get_or_create(
            lacquer_code=exteriorcolor.lacquer_code_body)
        exteriorcolor.lacquer_code_body_link = lacquer_code_body
        if exteriorcolor.lacquer_code_roof:
            lacquer_code_roof, created = Color.objects.get_or_create(
                lacquer_code=exteriorcolor.lacquer_code_roof)
            exteriorcolor.lacquer_code_roof_link = lacquer_code_roof
        exteriorcolor.save()


class Migration(migrations.Migration):

    dependencies = [
        ('mplate_decoder', '0024_auto_20200405_1415'),
    ]

    operations = [
        migrations.RunPython(link_colors),
    ]
