# Generated by Django 2.2.11 on 2020-04-07 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mplate_decoder', '0025_transfer_colors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mplate',
            name='aggregate_code',
            field=models.CharField(help_text='Engine and gearbox aggregate code', max_length=2, verbose_name='Aggregate'),
        ),
    ]
