# Generated by Django 2.2.11 on 2020-04-08 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mplate_decoder', '0026_auto_20200407_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mplate',
            name='model',
            field=models.CharField(help_text='Vehicle model code', max_length=4, verbose_name='Vehicle model'),
        ),
    ]
