# Generated by Django 2.2.11 on 2020-04-08 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mplate_decoder', '0027_auto_20200408_2115'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mplate',
            old_name='model',
            new_name='model_code',
        ),
    ]
