# Generated by Django 2.2.11 on 2020-04-08 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mplate_decoder', '0028_auto_20200408_2117'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Type2Model',
        ),
        migrations.DeleteModel(
            name='Type2ModelConfiguration',
        ),
        migrations.DeleteModel(
            name='Type2ModelExtra',
        ),
    ]
