# Generated by Django 2.2.11 on 2020-04-09 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mplate_decoder', '0029_auto_20200408_2130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mplate',
            old_name='export_destination',
            new_name='export_destination_code',
        ),
    ]
