# Generated by Django 2.2.11 on 2020-04-09 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mplate_decoder', '0030_auto_20200409_0312'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mplate',
            old_name='production_date',
            new_name='production_date_code',
        ),
    ]
