# Generated by Django 2.2.11 on 2020-05-06 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mplate_decoder', '0031_auto_20200409_0344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vwtype2model',
            name='m_codes',
            field=models.CharField(blank=True, help_text='List of M-codes for the corresponding extras', max_length=100),
        ),
    ]
