# Generated by Django 3.0.6 on 2020-05-12 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mplate_decoder', '0032_auto_20200506_0225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exportdestination',
            name='destination',
            field=models.CharField(blank=True, max_length=70),
        ),
    ]
