# Generated by Django 3.0.6 on 2020-05-12 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mplate_decoder', '0033_auto_20200512_0311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mplate',
            name='destination_country',
            field=models.CharField(blank=True, help_text='Country of destination', max_length=70),
        ),
    ]
