# Generated by Django 5.2.17 on 2026-10-06 04:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mplate_decoder", "0034_auto_20200512_0317"),
    ]

    operations = [
        migrations.AddField(
            model_name="mplate",
            name="decoded_model",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                help_text="Decoded vehicle model",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="mplate_decoder.vwtype2model",
            ),
        ),
    ]
